# Generated by Django 6.0.2 on 2026-02-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rango", "0002_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="", unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
